name: quiz_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  crypto: ^3.0.3
  dart_frog: ^0.3.0
  dart_jsonwebtoken: ^2.7.1
  deep_pick: ^1.0.0
  email_validator: ^2.1.17
  mongo_dart: ^0.9.1
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
